Thrift: The Missing Guide
=========================
Diwaker Gupta <me@diwakergupta.info>
{localdate}:
Written against Thrift 0.6.0

From the http://thrift.apache.org[Thrift website]:
[quote]
Thrift is a software framework for scalable cross-language services development.
It combines a software stack with a code generation engine to build services
that work efficiently and seamlessly between C++, Java, Python, PHP, Ruby,
Erlang, Perl, Haskell, C#, Cocoa, JavaScript, Node.js, Smalltalk, and OCaml.

Thrift is clearly abundant in features. What is sorely lacking though is _good_
documentation. This guide is an attempt to fill that hole. But note that this is
a reference guide -- for a step-by-step example on how to use Thrift, refer to
the Thrift tutorial.

Many aspects of the structure and organization of this guide have been borrowed
from the (excellent)
http://code.google.com/apis/protocolbuffers/docs/proto.html[Google Protocol
Buffer Language Guide]. I thank the authors of that document.

A link:thrift.pdf[PDF version] is also available.

.Copyright

Copyright (C) 2011 Diwaker Gupta

This work is licensed under the
http://creativecommons.org/licenses/by-nc/3.0/[Creative Commons
Attribution-NonCommercial 3.0
Unported License].

.Contributions

I welcome feedback and contributions to this guide. You can find the
https://github.com/diwakergupta/thrift-missing-guide[source code]
over at http://github.com[GitHub]. Alternatively, you can file a
https://github.com/diwakergupta/thrift-missing-guide/issues[bug].

.Acknowledgements

I thank the authors of Thrift for the software, the authors of the Google
Protocol Buffer documentation for the inspiration and the Thrift community for
the feedback. Special thanks to Dave Engberg from Evernote for his input.

.About the Author

I'm an open source geek and a software architect. I blog over at
http://floatingsun.net[Floating Sun] and you can find more about me
http://diwakergupta.info[here].

Language Reference
------------------
include::language-reference.asciidoc[]

Generated Code
--------------

This section contains documentation for working with Thrift generated code in
various target languages. We begin by introducing the common concepts that are
used across the board -- these govern how the generated code is structured and
will hopefully help you understand how to use it effectively.

Concepts
~~~~~~~~
include::code-concepts.asciidoc[]

Java
~~~~
include::code-java.asciidoc[]

C++
~~~
include::code-cpp.asciidoc[]


Other Languages
~~~~~~~~~~~~~~~

Python, Ruby, Javascript etc.

Best Practices
--------------
include::best-practices.asciidoc[]

Resources
---------

* http://thrift.apache.org/static/thrift-20070401.pdf[Thrift whitepaper]
* http://wiki.apache.org/thrift/Tutorial[Thrift Tutorial]
* http://wiki.apache.org/thrift[Thrift Wiki]
* http://code.google.com/apis/protocolbuffers/docs/overview.html[Protocol
  Buffers]
